name: Run flake8

on:
  pull_request:
    branches: [ "main" ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements.dev.txt
      - run: flake8 .
