name: Run Pyright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements.dev.txt
      - uses: jakebailey/pyright-action@v1
